### ISSUE TITLE
Apple rejected subscription sign-up screen

### ISSUE THREAD

**Issue by gahms** [schedjoules/ios-public-calendars-sdk#122]
Apple has rejected our iOS app during review due to the layout or wording of the subscription sign-up page.

From Apple:

> Jan 31, 2020 at 11:59 PM
From Apple
3. 1.2 Business: Payments - Subscriptions
Guideline 3.1.2 - Business - Payments - Subscriptions

We noticed that one or more of your auto-renewable subscriptions is marketed in a manner that may mislead or confuse users about the subscription terms or pricing. 

Specifically, your app offers a free trial or introductory period but does not make it clear that a payment will be automatically initiated for the next subscription period.

Next Steps

To resolve this issue, please revise your auto-renewable subscription purchase flow to clearly indicate how long the free trial lasts and the amount that will be billed after the free trial is over. 

Resources

The Apple Developer website includes detailed resources on how to offer auto-renewable subscriptions in your app. You can learn more about creating a positive onboarding experience for your customers in the Subscriptions Human Interface Guidelines.

Please see attached screenshot for details.
![attachment-13319121616723364035Screenshot-0131-145903](https://user-images.githubusercontent.com/5833431/73608655-f46ed700-45c5-11ea-9613-a9e2d253b3d6.png)

**Comment by wilfredstegeman** [comment]
Can you please ask the review team to look at the text in the footer of the screen. It states the following:

> you will automatically be billed the amount listed above through iTunes at the end of the free trial period which is 1 month. Your subscription will auto-renew unless you cancel or turn off auto-renew at least 24 hours before the end of the current period.

This makes clear that a payment will be automatically initiated for the next subscription period. If this doesn't say it, what would say it then in their opinion?

**Comment by Edhoru** [comment]
@gahms

**Comment by gahms** [comment]
Ok, sorry for the delay. Out of frustration I tried submitting a new version with a modified sign-up screen (attached below). This was rejected again, still without much information. Then I asked them to clarify what the actual problem was.

Their response was 
> the free trial is more prominent than the billed amount which could potentially mislead users. To resolve this issue, please revise your auto-renewable subscription to make the billed amount more prominent.

I did already submit a comment on the case, stating that their own examples does not fulfill their stated requirement, but I do not expect that to help.

So I think my next course of action will be to increase the font size of the "Billed..." label and make it bold and make the "Free trial" labels smaller and non-bold.

I will let you know how they respond.

![attachment-11078370023677996135Screenshot-0203-144546](https://user-images.githubusercontent.com/5833431/74083497-10aac200-4a65-11ea-9933-2739740d9e81.png)

**Comment by gahms** [comment]
BTW, the documentation they referred to was this:
https://developer.apple.com/design/human-interface-guidelines/subscriptions/overview/

**Comment by gahms** [comment]
I changed the subscription screen to look like the attached below. Now the app was approved.

![Simulator Screen Shot - iPhone 8 - 2020-02-08 at 20 57 27](https://user-images.githubusercontent.com/5833431/74091264-d4538200-4ab5-11ea-95a4-708f02d1f255.png)
