### ISSUE TITLE
'Featured' on top of home screen not localised

### ISSUE THREAD

**Issue by rutgerg** [schedjoules/ios-public-calendars-sdk#129]
The word 'featured' does not seem to be translated. Is that on purpose? Where is it set?
![Screenshot 2020-04-25 at 08 56 34](https://user-images.githubusercontent.com/676860/80273495-bcfa5d00-86d2-11ea-8ded-bf1d789ed165.png)

**Comment by rutgerg** [comment]
Idem for 'Search'

**Comment by wilfredstegeman** [comment]
Is it this one?
https://london.schedjoules.com/posts/139/edit?locale=en

**Comment by rutgerg** [comment]
@Edhoru where does this text come from?
