### ISSUE TITLE
Calendar Store SDK running on iOS 15

### ISSUE THREAD

**Issue by rutgerg** [schedjoules/ios-public-calendars-sdk#147]
Just installed the latest Calendar Store SDK running on iOS 15.

There are a few small issues (such as the tabBar at the bottom being transparent) that I have just fixed myself.

However, the main problem is that in iOS 15 when subscribing to a calendar, the user is still taken out of the app and into the native Apple Calendar app to set up the subscription!

Have you looked into stopping this behaviour happening?

**Comment by Edhoru** [comment]
Transparent buttons were a setup issue, removing Automatic signature fix it
