### ISSUE TITLE
Uploading app to the store rejected due to missing authorization from FIFA

### ISSUE THREAD

**Issue by mahudhud5** [schedjoules/ios-public-calendars-sdk#148]
We tried to submit our app to the store but we faced rejection from apple review team side due to the public calendars that we are using 

Their issue specifically is regarding using “World Cup” term without the necessary authorization from FIFA.

We tried to convince them that we are using only match name and date and nothing more ,, but they still want us to either attaching documentary evidence and provide our FIFA contact information in the App Review Information section in App Store Connect 

And the second option is removing the ‘World Cup’ calendar.

Waiting for your response and help to proceed with our build.

![image](https://user-images.githubusercontent.com/118801761/203257233-cd9d634a-cdf5-4e93-814e-42ebaf8996cd.png)

**Comment by rutgerg** [comment]
Hi @mahudhud5 which app is this?

**Comment by mahudhud5** [comment]
Hi @rutgerg 
I sent an email to support@schedjoules.com contains all the details and the API key we are using 
Could you check it

**Comment by mahudhud5** [comment]
https://apps.apple.com/us/app/icalendar/id492076105

@rutgerg
