### ISSUE TITLE
Ask notification permission

### ISSUE THREAD

**Issue by rutgerg** [schedjoules/ios-public-calendars-sdk#41]
@wilfredstegeman commented on [Thu Mar 14 2019](https://github.com/schedjoules/ios-public-calendars-sdk-int/issues/37)

Is currently asked after the intro pages.

**Comment by Edhoru** [comment]
Implementation will be just in our apps
Analytics:
- Get info about people response from notification prompt
- Users interaction with the notification

Deeplinking from the notification will be done in a future task
