### ISSUE TITLE
Add individual events to calendar

### ISSUE THREAD

**Issue by rutgerg** [schedjoules/ios-public-calendars-sdk#42]
@wilfredstegeman commented on [Thu Mar 14 2019](https://github.com/schedjoules/ios-public-calendars-sdk-int/issues/38)

Is the current SDK available when you swipe an event to the left. Clicking this option currently causes the app to crash.

![download-event](https://user-images.githubusercontent.com/5968782/54358324-5944da00-4660-11e9-9642-389ddaba6550.jpeg)

**Comment by Edhoru** [comment]
We don't have swipe on cells, I think we can either close this one, or implement the feature
