### ISSUE TITLE
Diagnostics in feedback email

### ISSUE THREAD

**Issue by rutgerg** [schedjoules/ios-public-calendars-sdk#52]
@wilfredstegeman commented on [Thu Mar 14 2019](https://github.com/schedjoules/ios-public-calendars-sdk-int/issues/46)

Example Diagnostics
App: AutoCal (com.schedjoules.f12012/5)
UUID: FDD1F07C-1DBA-426A-96D5-3DEADF9331F5
SubscriptionId: (null)
Device: iPhone
Firmware: 12.1.4
Library: 2.2.3 (5c08255)
URL: https://api.schedjoules.com/pages/22257777?locale=en&location=mc
Date: Thu, 14 Mar 2019 12:37:46 +0100
Locale: en_MC
Location: mc
TimeZone: Europe/Belgrade

**Comment by Edhoru** [comment]
Pre-fill this information into the body of the support email
