### ISSUE TITLE
Weather Calendars

### ISSUE THREAD

**Issue by rutgerg** [schedjoules/ios-public-calendars-sdk#53]
@wilfredstegeman commented on [Fri Mar 15 2019](https://github.com/schedjoules/content/issues/104)

**Comment by Edhoru** [comment]
@rutgerg how can I get this info, do we need a different endpoint?

**Comment by rutgerg** [comment]
Weather endpoint is different. You can fin description at https://github.com/schedjoules/calendar-store-api/blob/master/details/weather.md

**Comment by Edhoru** [comment]
Thanks

**Comment by rutgerg** [comment]
Think about:
- UI/UX
- Settings
- Location change
- GPS access

**Comment by Edhoru** [comment]
Use apple maps for reverse geolocation
