### ISSUE TITLE
Correct UX for when user has subscription but has not yet restored

### ISSUE THREAD

**Issue by rutgerg** [schedjoules/ios-public-calendars-sdk#72]
I download the Feestdagen app
I press subscribe to calendar
Free trial screen pops up
I press continue
I get notification that I'm already subscribed
I press ok
Now I get 'error, user cancelled the request'

If iphone knows I'm susbcribed why does erro follow?
If iphone knows I'm subscribed why is not restore process started or user pointed to restore process

**Comment by wilfredstegeman** [comment]
After I've clicked 'Restore purchases' I can't subscribe to a calendar. When I click a + sign or the subscribe button, the free trial intro screen is shown briefly and then it disappears again.

Check screencast at:
https://www.dropbox.com/s/j9rr5fk0jlnelfq/RPReplay_Final1558688247.MP4?dl=0

**Comment by Edhoru** [comment]
@wilfredstegeman do you have in app purchases enable?

**Comment by wilfredstegeman** [comment]
Yes, I had the in-app purchases enabled.
